### ISSUE TITLE
xml output indentation

### ISSUE THREAD

**Issue by fernoftheandes** [paxtonhare/MarkLogic-Sublime#18]
It would be great if the following xquery formatting options would work. Currently, specifying them does not make any difference.

`declare option xdmp:output "indent=yes";`
`declare option xdmp:output "indent-untyped=yes";`

**Comment by fernoftheandes** [comment]
Hi Paxton, did this turn out to be a bigger implementation issue than originally thought?

**Comment by paxtonhare** [comment]
No. I just got busy with paid work. It's on my list to push out a release
this week. It will be in there.

**Comment by fernoftheandes** [comment]
Much appreciated!!

**Comment by fernoftheandes** [comment]
How strange!! Even after installing and re-installing the plugin, via package control or manually (and making sure to re-start Sublime before and after the removal and re-installation), I still cannot have Sublime recognize the commands or the package settings for the plugin. The plugin is listed by the package control and lives inside Sublime's Installed Packages directory but no cigar: commands/snippets are not listed, Ctrl+Alt+r does not work, searching or opening api docs don't work...nada, nothing, niente!

Any ideas??? This all used to work fine...the only difference for me now is that I have a registered license of Sublime!

**Comment by dmcassel** [comment]
@fernoftheandes, what version of Sublime are you running? What OS?

**Comment by paxtonhare** [comment]
And also check the Sublime console output for any clues. crtl + Backtick on
Mac (can't type one from my phone).

**Comment by fernoftheandes** [comment]
Sublime 3 (build 3065) on Mac OS 10.7.5...no messages on Sublime console. Except for the package being listed and present in the install directory, there are really no indications that Sublime recognizes the plugin commands/snippets, etc. at all.

**Comment by paxtonhare** [comment]
@fernoftheandes, I just discovered a nasty bug #25 when running from Package Control. The fix is in 1.1.9 but I think Package control takes about an hour to pick up the new version. Let me know if that happens to fix it.

**Comment by fernoftheandes** [comment]
Hi Paxton,

Unfortunately, this did not fix my problem. I re-started Sublime after removal of 1.1.8 and after installation of 1.1.9 and things are still the same for me: package is listed, present in Installed Packages dir, but no commands, snippets, Run at Server functionality...blank.

**Comment by fernoftheandes** [comment]
I am assuming you are testing with Sublime 2 and not 3, is that correct?

**Comment by paxtonhare** [comment]
I'm using Sublime 3. But I have tested with 2 as well.

**Comment by fernoftheandes** [comment]
**Here is what is output to the console when I remove the MarkLogic package:**

* reloading Packages/User/Package Control.sublime-settings
* reloading Packages/User/Preferences.sublime-settings
* found 1 files for base name Default.sublime-theme
* theme loaded
* reloading Packages/User/Package Control.sublime-settings
* Traceback (most recent call last):
  * File "package_control.commands.remove_package_command in /Users/nivaldo/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 76, in unignore_package
 * File "package_control.package_disabler in /Users/nivaldo/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 145, in reenable_package
  * File "package_control.events in /Users/nivaldo/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 69, in clear
  * File "package_control.events in /Users/nivaldo/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package", line 64, in do_clear
* KeyError: 'MarkLogic'

**And here is what is output to the console when I re-install the package:**

* reloading Packages/User/Package Control.sublime-settings
* reloading Packages/User/Preferences.sublime-settings
* found 1 files for base name Default.sublime-theme
* theme loaded
* reloading Packages/User/Package Control.sublime-settings

**Comment by paxtonhare** [comment]
One thing I've read after some googling is to remove the User directory
under your package directory. Preferences -> Browse Packages.

Please back it up and don't just delete it. After it's gone I suggest you
reinstall the Marklogic plugin and see if it starts working. If it works
then you can go through the fun exercise of seeing what changed in your
User dir that messed it up.

**Comment by fernoftheandes** [comment]
Thanks Pax :) 

I am going to try that and report back...

**Comment by fernoftheandes** [comment]
That did it! Got rid of the User directory and the installation of the MarkLogic plugin was completely successful. And the indented output is working just right. Thanks and please feel free to close this issue. This one is behind us.
