### ISSUE TITLE
Linting library modules?

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [paxtonhare/MarkLogic-Sublime#22]
Apologies if this was already covered elsewhere, but I couldn't find an existing issue.

Is there a way to get MarkLogic to lint library modules? I get this exception:

`XDMP-EVALLIBMOD: xdmp:eval("xquery version &quot;1.0-ml&quot;;&#10;module namespace controll...", (), <options xmlns="xdmp:eval"><default-xquery-version>app-server</default-xquery-version><stat...</options>) -- Cannot evaluate library module:`

Thanks!

**Comment by paxtonhare** [comment]
Are you running the lint command? It looks from the error like you are simply trying to execute the code. The lint command can handle library modules.

**Comment by JKesMc9tqIQe9M** [comment]
I'll double-check, but I was pretty sure I was linting -- this is happening in the background (as specified by the lint mode) and I see the error in the ST3 console. I'm not actually doing anything explicit to cause it to happen.

FWIW, I get the same exception if I try linting via MarkLogic when using oXygen.

**Comment by JKesMc9tqIQe9M** [comment]
I'm definitely linting here (or rather, MarkLogic-Sublime is -- in the background). But I'm stumped. I still can't get it to lint a library module, and almost all the code I work with is in library modules.

Seems like other folks have run into this problem, _eg_ http://maxdewpoint.blogspot.com/2012/08/static-checking-library-module.html. /cc @ryanjdew

**Comment by paxtonhare** [comment]
Linting a library module is working for me. Let's try to troubleshoot.
First, which version of Sublime and which version of the MarkLogic plugin
are you using?

Assuming those are both current then it is likely the code that checks to
see if the current bit of code is a library module or not. It could be that
you have exposed a bug in my regex to determine this.

I'd be curious to see the prolog of your module.

**Comment by JKesMc9tqIQe9M** [comment]
I think I'm OK on versions: ST3 build 3065 and v 1.1.7 of your ST plugin.

Your comment about the regex for the prolog seems like it might be on point. I noticed that I had a comment at the top of the module:

```
xquery version "1.0-ml";

(:~ 
  comment here
:)
module namespace xxxx = "XXXXXXXXXXX";

... etc
```

With that comment there, I get the original exception (XDMP-EVALLIBMOD). When I remove the comment, I get a new exception: XDMP-MODNOTFOUND -- it's complaining about the first import I have in the module, saying it can't find the module I'm trying to import. So at least the comment seems to be what's causing the original problem. Now I have a new problem.

More background: this is a Roxy project, but one where the modules are being kept locally on the filesystem. Will it be possible to lint stuff in this scenario?

Thanks again for your help with this.

**Comment by paxtonhare** [comment]
I missed this last reply. I haven't tested it against a filesystem setup. Only against modules db. In theory it should work, but I can't be sure. The one thing to check is that the modules that it can't find are already deployed to the filesystem. If I can find some spare time I'll try it locally with the filesystem.

**Comment by JKesMc9tqIQe9M** [comment]
OK, thanks for the reply. It's possible in my particular case there are two problems: the filesystem aspect and then module imports without 'at' locations (uses MarkLogic's module location config in an app server instead). 

If it's possible to get the filesystem piece working them I'm guessing the second part should be pretty easy to solve.
