### ISSUE TITLE
Enhancement: support public/private annotations

### ISSUE THREAD

**Issue by prestonmcgowan** [paxtonhare/MarkLogic-Sublime#33]
http://www.w3.org/TR/xquery-30/#doc-xquery30-Annotation

Please support syntax highlighting for "public" and "private" annotations in function and variable declarations.

**Comment by paxtonhare** [comment]
What do you mean by support? Make the color somehow different?

**Comment by prestonmcgowan** [comment]
right now "private" is not styled where as declare function is styled.

**Comment by prestonmcgowan** [comment]
![image](https://cloud.githubusercontent.com/assets/1315891/6446783/4e6cea6e-c0db-11e4-904a-8636ffd6a7dd.png)

**Comment by prestonmcgowan** [comment]
I am also seeing switch and case not being highlighted. (XQuery 3.0 stuff)

![image](https://cloud.githubusercontent.com/assets/1315891/6447352/927a2ea2-c0df-11e4-8cc4-12b73d251475.png)

**Comment by paxtonhare** [comment]
fixed in develop branch
